---

name: lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  PSScriptAnalyzer:
    runs-on: windows-latest

    permissions:
      pull-requests: write

    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Setup Reviewdog
        uses: reviewdog/action-setup@v1.5.0

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@v1.0
        with:
          path: .\
          recurse: true
          output: PSScriptAnalyzer.sarif

      - name: Convert SARIF URIs to relative
        shell: pwsh
        run: |
          $cwd = (Get-Location).Path
          $rootUri = (New-Object System.Uri($cwd)).AbsoluteUri.TrimEnd('/')
          (Get-Content PSScriptAnalyzer.sarif -Raw) `
            -replace [regex]::Escape("$rootUri/"), '' `
            | Set-Content PSScriptAnalyzer.rel.sarif

      - name: Review by PSScriptAnalyzer outputs
        shell: pwsh
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          Get-Content PSScriptAnalyzer.rel.sarif |
            reviewdog -f=sarif -reporter=github-pr-review

  YAMLLint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: YAMLLint
        uses: karancode/yamllint-github-action@v2.1.1

  markdown-lint:
    name: Lint markdown files.

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: DavidAnson/markdownlint-cli2-action@v20

  Blinter-simple-output:
    name: Lint batchfiles.

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v7.2.0

      - run: uv venv

      - run: |
          uv pip install \
          git+https://github.com/MinoruSekine/Blinter-simple-output.git@d685af5

      - run: |
          uv run blinter-simple-output --style github-annotation toast-cli.cmd
